[workspace]
members = ["crates/semath-core", "crates/semath-native", "crates/semath-wasm"]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"
repository = "https://github.com/corca-ai/semath"
version = "0.16.0"

[workspace.dependencies]
regex = "1.11.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
thiserror = "2.0.14"
wasm-bindgen = "=0.2.100"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
